# Generated by Django 5.0.6 on 2024-06-29 03:33

from django.db import migrations

import api.models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", api.models.UserManager()),
            ],
        ),
    ]
