# Generated by Django 5.0.6 on 2024-06-26 05:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_user_email_verified"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"verbose_name": "News"},
        ),
    ]
